### ISSUE TITLE
TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by jtrent238** [beurtschipper/Depix#54]
The image I try to use:
![](https://i.imgur.com/O4U2JtB.png)

Command entered:
```python depix.py -p test.png -s images/searchimages/debruinseq_notepad_Windows10_closeAndSpaced.png -o output.png```

```$ python depix.py -p test.png -s images/searchimages/debruinseq_notepad_Windows10_closeAndSpaced.png -o output.png
INFO:root:Loading pixelated image from test.png
Traceback (most recent call last):
  File "C:\Users\Admin\git\Depix\depix.py", line 27, in <module>
    pixelatedImage = LoadedImage(pixelatedImagePath)
  File "C:\Users\Admin\git\Depix\depixlib\LoadedImage.py", line 13, in __init__
    self.loadImageData()
  File "C:\Users\Admin\git\Depix\depixlib\LoadedImage.py", line 42, in loadImageData
    self.imageData[x][y] = rawData[rawDataCount][0:3]
TypeError: 'int' object is not subscriptable
```

**Comment by beurtschipper** [comment]
I believe this issue comes up when you have an image with only greyscale, making every pixel an integer instead of a tuple.
