### ISSUE TITLE
KeyError: '' ValueError: unknown file extension:

### ISSUE THREAD

**Issue by Aran8276** [beurtschipper/Depix#65]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\Image.py", line 2144, in save
    format = EXTENSION[ext]
KeyError: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\Depix-main\depix.py", line 82, in <module>
    unpixelatedOutputImage.save(args.outputimage)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\Image.py", line 2146, in save
    raise ValueError(f"unknown file extension: {ext}") from e
ValueError: unknown file extension:

**Comment by Aran8276** [comment]
I realized that i forgot to put the file extension and name, at the output
